name: Checks

on:
  pull_request:
    paths:
      - '*'
      - '*/*'
      - '*/*/*'
      - '*/*/*/*'
      - '*/*/*/*/*'
      - '*/*/*/*/*/*'
      - '!/devops/*'

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.1'

      - name: Install
        run: yarn install

      - name: TypeCheck
        run: yarn mctl check:typecheck

      - name: Lint
        run: yarn mctl check:lint

      - name: Test
        run: yarn mctl check:test
